engines:
  bandit:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
    exclude_patterns:
      - "**/externals/"
  shellcheck:
    enabled: true
    